modLoader = "javafml"
loaderVersion = "[1,)"
issueTrackerURL = "https://github.com/architectury/ClothConfig/issues/"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/cloth-config-forge/"
logoFile = "icon.png"
authors = "shedaniel"
license = "GNU LGPLv3"

[[mods]]
modId = "cloth_config"
version = "${version}"
displayName = "Cloth Config v16 API"
description = '''
An API for config screens.
'''

[[dependencies.cloth_config]]
modId = "neoforge"
type = "required"
versionRange = "[21.2.0-beta,)"
ordering = "NONE"
side = "BOTH"
